### PR TITLE
add support for ventilation

### PR DESCRIPTION
**Pull request by aaschmid**
Update: Just finished the PR by adding some tests.

---- 
Questions before I will finish it with tests, documentation etc.:

* Does anyone now what the difference between `deviceType` `"TCU"` and `"ventilation"` is? Especially you currently only support `"tcu"` but on my `"ViAir..."` there also appears a device written in upper case... -> ignored for now
*  Are there any coding guidelines or standards you follow? -> just used the defaults of my Intellij
* You do use `mypy` but I haven't seen any type annotations in the code so far? Should I type - at least new code - or not? -> currently not done

Cheers

### CODE REVIEW

**Comment by aaschmid** [comment]
@woehrl01 @crazyfx1 @oischinger @somm15: Anyone?

**Comment by pduchnovsky** [comment]
@woehrl01 @crazyfx1 @oischinger @somm15 

If you find some time to look in to this that would be great guys and thanks for your great work !

**Comment by dusan-ivanco** [comment]
@somm15 can you look at this please?

**Comment by CFenner** [comment]
Unfortunately, there seems not to be that much activity on the repository. 

What about adding a sample response of the device.

**Comment by edeckert** [comment]
@CFenner 
I added today a pull request for testing my heatpump (vitocal 333-g). In this file there is also a ventilation system (vitovent 300-w). Or should I upload an extra file for my ventilation system?

I tested the vitovent 300-w with this pull request and it worked as already described here:
https://github.com/somm15/PyViCare/issues/321

@aaschmid  Please mark this PR as ready for review so @somm15 can review this PR.

**Comment by aaschmid** [comment]
Done, however I doubt any progress as any vital signs kept absent since a while ;-)

**Comment by CFenner** [comment]
Maybe it's time to have a fork of this to continue the great work.

**Comment by woehrl01** [comment]
@CFenner there is no need to create a fork. If someone wants to join @crazyfx1 and me as maintainers feel free to reach out. We both are currently just busy with our daytime jobs.

**Comment by CFenner** [comment]
Great, I know it can be challenging to maintain open source, but then it's good to share the load. 
I think I would be able to help you with that to some extent.

Would be nice to evolve this library and the related Home Assistant integration further.

**Comment by crazyfx1** [comment]
The PR looks fine code-wise. Can you please add unit tests for your device?

**Comment by aaschmid** [comment]
Yes, I can. Just waited for feedback from someone able to merge it. Otherwise, all the effort is kind of worthless...

**Comment by edeckert** [comment]
@aaschmid I have a Vitovent 300-W. Can you also add Unit Tests for my Ventilation System? You can find it in this file:
https://github.com/edeckert/PyViCare/blob/master/tests/response/Vitocal333G.json

**Comment by aaschmid** [comment]
@edeckert I can, but would need the correct file. The link points to a vitocal 333g which is a heat pump rather than a ventilation device ...

**Comment by edeckert** [comment]
@aaschmid the file has both in it. The Ventilation and the Heat Pump.

**Comment by aaschmid** [comment]
Ah, I see. As the `ventilation` stuff is rather easy to my file, I just added my file for now. You should now easily be able to add yours as copy of mine. Hope that is ok as well for you!

**Comment by woehrl01** [comment]
Thank you @aaschmid!

**Comment by Benleni17** [comment]
Hello guys,

is there something new?

**Comment by aaschmid** [comment]
What do you mean @Benleni17? Branch is merged and available for everyone...

**Comment by Benleni17** [comment]
> Wie meinst du das?@Benleni17? Die Filiale ist zusammengelegt und für alle verfügbar...

I'm looking for a solution for home assistant so that I can also use my Vitovent there

**Comment by aaschmid** [comment]
But this solution needs to be implemented into HomeAssistent, doesn't it?

I myself use Loxone and integreted all of my Viessmann devices using https://github.com/aaschmid/vicare-automation-server which works very well.

**Comment by CFenner** [comment]
There have been other [requests to support ventilation systems](https://github.com/home-assistant/core/issues/91417#issuecomment-1871402025) in the HA repository. Maybe you join there. But that guy has a heatpump with an attached ventilation component which [is not yet supported](https://github.com/somm15/PyViCare/pull/358).

**Pull request merged**
