### PR TITLE
add more programs to getPrograms

### PR DESCRIPTION
**Pull request by fb22**
add all available programs from vicare api: heating.circuits.N.operating.programs.XXX
Note: 'active' is not a program but it shows the current active operating program on the device therefore I have it removed.

### CODE REVIEW

**Comment by CFenner** [comment]
Is this documented somewhere in the ViCare API?

**Comment by fb22** [comment]
> Is this documented somewhere in the ViCare API?

see https://documentation.viessmann.com/static/iot/data-points

**Review by CFenner — APPROVED** [review]
👍

**Comment by crazyfx1** [comment]
Can you fix the tests please

**Comment by fb22** [comment]
> Can you fix the tests please

done

**Pull request merged**
