### PR TITLE
Implement frost protection active parameter

### PR DESCRIPTION
**Pull request by adorobis**
Based on:
```
         {
            "properties": {
                "status": {
                    "type": "string",
                    "value": "off"
                }
            },
            "commands": {},
            "components": [],
            "apiVersion": 1,
            "uri": "https://api.viessmann-platform.io/iot/v1/equipment/installations/xxxxx/gateways/yyyyy/devices/0/features/heating.circuits.0.frostprotection",
            "gatewayId": "yyyyy",
            "feature": "heating.circuits.0.frostprotection",
            "timestamp": "2021-07-16T02:00:06.254Z",
            "isEnabled": true,
            "isReady": true,
            "deviceId": "0"
        },
```

### CODE REVIEW

**Comment by crazyfx1** [comment]
Can you please update the existing response JSON (Vitodens200W.json) instead of creating a new one? After that please update the unit tests and create a unit test for the new property. Thanks!

**Comment by adorobis** [comment]
I have not created a new response json file. Above is just a comment on which feature I'm implementing. The file already includes this response.
Regarding the unit test - I'll try - I have never done that :)

**Comment by adorobis** [comment]
Updated the unit test for the new property, seems simple. As I've never done that before, how can I use those unit tests in my environment?

**Comment by woehrl01** [comment]
@adorobis the only thing you should need is to execute `pytest` from the root of the project.

**Comment by crazyfx1** [comment]
> I have not created a new response json file. Above is just a comment on which feature I'm implementing. The file already includes this response.

The existing file is called `response_Vitodens200W.json`. In this PR you are creating a new file called `v2_features_response_Vitodens200-W.json`. Maybe you did not update your fork.

**Comment by adorobis** [comment]
Well, I've sent this file in previous PR https://github.com/somm15/PyViCare/pull/100 which was merged already few days ago. I have updated my fork but for some reason this file is still there, not sure why. I think you have renamed it in https://github.com/somm15/PyViCare/pull/103/files but for some reason when I fetched from master repo my file has not been removed. I'll remove it manually now.

**Comment by adorobis** [comment]
Should be ok now.

**Comment by adorobis** [comment]
And thanks for info about pytest, all works now :) Let me update my ha with latest version of PyViCare :)

**Pull request merged**
