### PR TITLE
Adding Vitodens 300W data and test

### PR DESCRIPTION
**Pull request by jborup**
Please find a dataset from a Vitodens 300W and also the tests.

### CODE REVIEW

**Comment by woehrl01** [comment]
@jborup Thank you very much for the PR. I suppose that the code comments of the tests is because they are not supported for your device? Please change the tests so that they validate the not supported exception. After that, I'm happy to merge this in.

**Comment by jborup** [comment]
@woehrl01 added the exception validations, but I left the "desired" outcome, as this is what Viessmann really should provide, so i hope we could end up with this not being unsupported later :-)

**Comment by woehrl01** [comment]
Thanks @jborup as we already have tests in place for those attributes on the 200W where this is supported from Viessman, I, personally, prefer the comments to be removed. What you can do is to replace them with something like `Is currently (August, 2021) not supported by the Viessman API even though it works for the Vitodens 200W`. So, we remember that in the future.

**Comment by jborup** [comment]
@woehrl01 Last update for vitodens300W for now - take it or leave it:-)

**Review by woehrl01 — APPROVED** [review]
Thank you! Looks great 🚀

**Pull request merged**
