### PR TITLE
Add properties for heatingrod

### PR DESCRIPTION
**Pull request by crazyfx1**
Viessmann recently added the status of the electric heating rod in heatpumps to their API. 
This PR adds the properties to the heatpump class.

### CODE REVIEW

**Comment by crazyfx1** [comment]
@somm15 Can you please release a new version on pypi? Thanks :)

**Comment by somm15** [comment]
Uploaded to pip

**Comment by crazyfx1** [comment]
@somm15 Seems like something went wrong upgrading to pip. The properties are not available in the new version 0.2.3
Can you please check again? ;)

**Comment by somm15** [comment]
I could be that I'm so tired that I forgot to git pull first, sorry

**Pull request merged**
