### PR TITLE
Support Ventilation modes and programs on heat pumps

### PR DESCRIPTION
**Pull request by CFenner**
This copies the functions for ventilation modes and programs from the Ventilation device to Heat Pumps.

See: https://github.com/somm15/PyViCare/blob/63f9f7fea505fdf9a26c77c6cd0bff889abcdb05/tests/response/Vitocal222S.json#L3227-L3229

### CODE REVIEW

**Comment by CFenner** [comment]
@LarsTh86

**Comment by LarsTh86** [comment]
It is relevant that you activated it for a vitocall222s? We have a 200s. I don't know if this is relevant. I can test it tomorrow. At the moment the update from HA Core is on going. After this is finished, i will test it

**Comment by CFenner** [comment]
Unfortunately, you can only test this with a python script, not in Ha. 

Device type is determined by https://github.com/somm15/PyViCare/blob/63f9f7fea505fdf9a26c77c6cd0bff889abcdb05/PyViCare/PyViCareDeviceConfig.py#L82 which should also match your device. If the feature is not supported an exception will raise that is handled on HA.

**Comment by LarsTh86** [comment]
Is there something new about the Ventilation ?

**Comment by crazyfx1** [comment]
What is the ventilation on heatpumps?

**Comment by CFenner** [comment]
As far as I understand it's a central ventilation unit attached to the heat pump. 

@LarsTh86 can you elaborate a bit more on your setup?

**Comment by LarsTh86** [comment]
I have heatpump with direct connected central ventilation unit. vitocal 200-s with Vitovent 200-W and a VX3 hybrid storage system.

**Comment by LarsTh86** [comment]
There are two programs for ventilation, which would be really comfortable to control with the vicare integration for HA. I already activated and deactivate this Modus with iobroker but this is not comfortable but it works with vicare-api

**Comment by CFenner** [comment]
I‘m unsure if this is the right approach. For some reason the ventilation program is also shown in the heat pump but i think there is also a separate device for the vitovent!

**Comment by CFenner** [comment]
Ok, just verified again, the ventilation device is only accessible via the heating device. There is no separate device in the API.

[config_entry-vicare-a1c2d8d88e9e884a25242de183daac49-2.json](https://github.com/somm15/PyViCare/files/14323037/config_entry-vicare-a1c2d8d88e9e884a25242de183daac49-2.json)

**Comment by LarsTh86** [comment]
It is only controlled via the heat pump and is directly connected to the heat pump control.

**Comment by pduchnovsky** [comment]
I have the same setup as [LarsTh86](https://github.com/LarsTh86), vitocal 200-s with Vitovent 200-w
It's going to be awesome finally having control via HA once this is merged :)
Thanks [CFenner](https://github.com/CFenner) for awesome work on this

**Review by Nibot1 — APPROVED** [review]
Those changes look good and useful. I can also approve that there are many of those combined units, especially in prefabricated houses in Germany. The Heat pump and the Vent-Unit communicate internally via Modbus or something like this and don't have their own HMI

**Comment by LarsTh86** [comment]
Ready for testing?

**Comment by Asino123** [comment]
Hi, I have a Vitocal 200-S to which a vitvont 200-C is connected via Modbus which is correctly controlled by the ViCare app. I don't understand if currently with the home assistant integration I can control the ventilation because for now only the heat pump is displayed to me. Can anyone tell me if I'm doing something wrong? Thanks

**Comment by LarsTh86** [comment]
Not yet. This ticket was the feature request for the support. If you use for example use the iobroker, it will be supported. It is technically possible, but not yet implemented.But this is good time to ask for the actually state?Gesendet von Outlook für AndroidVon: Asino123 ***@***.***>Gesendet: Freitag, September 27, 2024 2:30:15 PMAn: openviess/PyViCare ***@***.***>Cc: LarsTh86 ***@***.***>; Mention ***@***.***>Betreff: Re: [openviess/PyViCare] Support Ventilation modes and programs on heat pumps (PR #358)
Hi, I have a Vitocal 200-S to which a vitvont 200-C is connected via Modbus which is correctly controlled by the ViCare app. I don't understand if currently with the home assistant integration I can control the ventilation because for now only the heat pump is displayed to me. Can anyone tell me if I'm doing something wrong? Thanks

**Comment by Asino123** [comment]
Thanks for the reply. Could you tell me what iobroker is or where I can find information about it? Thanks

**Comment by CFenner** [comment]
@Asino123 this means the vitovent is integrated into the aPI via the heatpump or a separate device?

**Comment by Asino123** [comment]
> @Asino123 this means the vitovent is integrated into the aPI via the heatpump or a separate device?

It is integrated via the heat pump.

**Comment by LarsTh86** [comment]
Iobroker is similar to homeassistant. Ans has also a vicare "integration" and this integration has a support for ventilation. This integration is not user friendly but it works. But nevertheless would be a integration in homeassistant would be great

**Comment by gabrielma89** [comment]
How can I add ventilation device to control it via HA? I have Vitocal 200 S and Vitovent 300-W.  My JSON is attached. 
[config_entry-vicare-01J75EPF713PYFB5DH0T9G5BWP.json](https://github.com/user-attachments/files/17519266/config_entry-vicare-01J75EPF713PYFB5DH0T9G5BWP.json)

**Pull request merged**
