### PR TITLE
RoomSensor and RadiatorActuator devices

### PR DESCRIPTION
**Pull request by oischinger**
Implementation of ZigBee sensors/actuators

Also added json responses for the thermostatic radiator valve and
Zigbee sensors.

### CODE REVIEW

**Comment by woehrl01** [comment]
@oischinger yes, makes sense, adding additional devices. In your case the if condition has to be `and` instead of `or`.

**Comment by oischinger** [comment]
@woehrl01 I updated the PR accordingly.

Contains now the implementation of RoomSensor and RadiatorActuator devices

**Comment by oischinger** [comment]
sorry for the force-push.
Had to rebase and fix a conflict.

**Comment by woehrl01** [comment]
Nice, looks great!

**Comment by oischinger** [comment]
@woehrl01 would you be able to create another PyViCare release anytime soon?
I'm working on multi-device support in the HA-integration and this would ease testing quite a bit.
Thanks!

**Comment by woehrl01** [comment]
Sure, I just published the version `2.23.0` a few minutes ago. Have fun! @oischinger

**Comment by tuxiano** [comment]
Hi, is this feature available through the official vicare integration of Home Assistant? Because I can't see/add radiator actors and room sensor.

**Pull request merged**
