### PR TITLE
Refactor circuits for auto detection and easier usage

### PR DESCRIPTION
**Pull request by woehrl01**
This PR is another breaking change. But it allows a much easier usage of all the circuits.

Changes:
1. Split up of the device in non-circuit and circuit dependent properties
2. Access the circuit properties via `device.circuits[0].getAbc()`

This allows iteration of all existing circuits via the new `.circuits` property. Circuits are accessed via an indexer.

### CODE REVIEW

**Comment by oischinger** [comment]
looks good. Is there a way to retrieve the available circuits from the API?
This way Home assistant could just go through what's available instead of having the user to configure them.

**Comment by woehrl01** [comment]
@oischinger Yes, that's already implemented `getActiveCircuits` I use that one to generate the backing list. That means you can simply iterate through all the `circuits`. I use that in the `test_Integration.py` 

To automatically iterate through all the available ones in Home Assistant was exactly my intention. What we need to modify in Home Assistant is that you can choose the circuit for `setMode`.

**Comment by oischinger** [comment]
perfect. I guess we need another release after this PR is merged :D

**Comment by woehrl01** [comment]
See `2.3`

**Pull request merged**
