### PR TITLE
chore(testdata): Update Vitocal 250A data

### PR DESCRIPTION
**Pull request by CFenner**
with advanced api plan

### CODE REVIEW

**Comment by stho** [comment]
Hi @CFenner,

does that mean that I need the advanced api plan to get data about power consumption?

```
            'heating.compressors.0.power.consumption.current',
            'heating.compressors.0.power.consumption.dhw',
            'heating.compressors.0.power.consumption.heating',
            'heating.compressors.0.power.consumption.total',
```

I have issues to get this information in the homeassistant integration for vicare.

**Comment by CFenner** [comment]
@stho you can find the tier level of the data points here: https://documentation.viessmann.com/static/iot/data-points

**Comment by CFenner** [comment]
Please note that consumption data is somehow broken in the Viessmann API. It stops working every night for some users.

**Comment by stho** [comment]
Ok, so I should be able to receive the consumption data. They are available in the basic tier.

Yeah, read the homeassistant issue on that, but wondered if there can be some issues on my end.

**Comment by CFenner** [comment]
I have legacy devices (VitoConnect, non-E3) and these do not provide consumption data.

**Pull request merged**
