### PR TITLE
Add api for solar collector

### PR DESCRIPTION
**Pull request by sweh**
Add api methods to get the current solar panel temperature and if the solar pump is running.

### CODE REVIEW

**Comment by crazyfx1** [comment]
Thanks for your contribution.

Are those calls tested with the V2 API?

**Comment by sweh** [comment]
Tested under V1 and V2.

**Comment by crazyfx1** [comment]
It would be great if you could add your V2 json response to the tests folder and add unit tests for the new properties.
We only need the V2 version, the V1 will stop working in 2 days. Also please don't forget to remove your gatewaySerial and installationId from the response.

**Comment by sweh** [comment]
> It would be great if you could add your V2 json response to the tests folder and add unit tests for the new properties.
> We only need the V2 version, the V1 will stop working in 2 days. Also please don't forget to remove your gatewaySerial and installationId from the response.

I extended the existing reponses json for a Vitodens 200W (which is the one I own) and added two lightweight test methods to the existing ones.

**Pull request merged**
