### PR TITLE
Create response_Vitodens222W.json

### PR DESCRIPTION
**Pull request by paradix**

### CODE REVIEW

**Comment by jborup** [comment]
@paradix would it be possible for you to extract this dataset again?
Looks like it is extracted with ' rather than ".
And also all booleans are without double quoutes("). Of course this can be fixed, but would suggest to pull a new extract if possible.

**Comment by paradix** [comment]
I hope now it formatted in the right way.

**Comment by jborup** [comment]
@paradix looks perfect now thanks :-)

**Comment by jborup** [comment]
@woehrl01 would you be able to do the merge on this one and then I will rename and add the test.

**Pull request merged**
