### PR TITLE
Create response_Vitodens333F

### PR DESCRIPTION
**Pull request by kruemel746**
JSON output features

### CODE REVIEW

**Comment by kruemel746** [comment]
Hope this works. First time with github!

**Comment by jborup** [comment]
@woehrl01 if you approve and rename this file to your expected path/name I have a test ready to be added.

**Comment by woehrl01** [comment]
@jborup im currently on the road. Feel free to rename. Thanks for your effort!

**Comment by jborup** [comment]
@woehrl01 np PR made #141

**Pull request merged**
