### PR TITLE
Proposal for batching requests

### PR DESCRIPTION
**Pull request by crazyfx1**
To overcome the Viessmann API limits I implemented a proposal for batching (issue #22)

I noticed that the normal call to the "features" endpoint already delivers all data, so there is no need to call each feature on its own.

Example:
```Python
t=HeatPump("xxx","xxx","token.save")
t.fetchAndCacheFeatures()
print(t.getDomesticHotWaterConfiguredTemperature()) 
```

Returns the same result as before.
Naming can be improved, but I couldnt come up with something else.

@oischinger Also looking forward to your feedback ;)

### CODE REVIEW

**Comment by oischinger** [comment]
Nice finding @crazyfx1 . I'm testing it right now in combination with the Home Assistant integration and it seems to work as expected. 
From a library perspective I would however expect that people might be confused calling getProperty and never getting any new values.
Maybe we should call it getPropertyCached then and keep the existing getProperty as is?

**Comment by crazyfx1** [comment]
Good point. But in my opinion the library was never playing fair with the API servers so I personally would not provide the old way of fetching data anymore. Maybe the owner should decide ;)

**Comment by adorobis** [comment]
great @crazyfx1 !
Have you also made updates to the HA integration to use the new function?

**Comment by oischinger** [comment]
The adaptions are straight forward. Just call t.fetchAndCacheFeatures() as the first thing in the climate and water heater component.

I'm currently testing it with a 40 seconds update interval. Let's see if I get banned before 24h ;)

**Comment by paradix** [comment]
> The adaptions are straight forward. Just call t.fetchAndCacheFeatures() as the first thing in the climate and water heater component.
> 

I have been running this since 10 am this morning with a 60 sec interval. So far so good ;)

@oischinger does adding t.fetchAndCacheFeatures() to water and climate causes the api call to be done twice each 60 sec?

**Comment by oischinger** [comment]
@paradix:

Yes it does. That's not optimal on the other hand it might still suffice.
What should be considered is that some people have multiple climate devices which would have to be perform different api calls anyway.
Therefore I believe a configurable scan interval is necessary for those not-so-common installations

**Comment by paradix** [comment]
@oischinger is it possible to make the scan interval somehow configurable?

**Comment by crazyfx1** [comment]
True I haven't thought about the water heater doing it's own API calls.
Since you only have 1450 calls per 24h (which is 1 per minute) you can't have both water heater and climate with scan_interval of 60.

Maybe we need another solution which shares the cache between PyViCareService instances.

**Comment by paradix** [comment]
After about 14h of working fine with the 60s interval for climate and a 900s interval for water I got blocked by the api

**Comment by oischinger** [comment]
Same here. I have my doubts about the 1450 calls limit...
But maybe I already used up lots of calls from the 24h period before switching to this pr

**Comment by crazyfx1** [comment]
Other calls might are also be counted:
- The "get-installations" call (i'm not sure how often thats called actually)
- Setting temperatures 
- Getting new access tokens?

**Comment by adorobis** [comment]
> After about 14h of working fine with the 60s interval for climate and a 900s interval for water I got blocked by the api

There must have been some disruption to the viessmann service, mine was not working in the morning neither and now is working again. I still have only the version with polling every 15 minutes

**Comment by adorobis** [comment]
> Same here. I have my doubts about the 1450 calls limit...
> But maybe I already used up lots of calls from the 24h period before switching to this pr

But isn't the HA adding always 2 devices (the climate and water heater) by default? At least this is happening in my case. It will have 2 API calls every minute or am I misunderstanding something?

**Comment by crazyfx1** [comment]
> > After about 14h of working fine with the 60s interval for climate and a 900s interval for water I got blocked by the api
> 
> There must have been some disruption to the viessmann service, mine was not working in the morning neither and now is working again. I still have only the version with polling every 15 minutes

I dont think the 15min version can even run 24h. The climate device alone does 16 requests per update and the water heater 3, so we have too many requests in the current version aswell ;)

**Comment by paradix** [comment]
> > After about 14h of working fine with the 60s interval for climate and a 900s interval for water I got blocked by the api
> 
> There must have been some disruption to the viessmann service, mine was not working in the morning neither and now is working again. I still have only the version with polling every 15 minutes

Yes that't true, mine is back working again without the 24h penalty.



> > > After about 14h of working fine with the 60s interval for climate and a 900s interval for water I got blocked by the api
> > 
> > 
> > There must have been some disruption to the viessmann service, mine was not working in the morning neither and now is working again. I still have only the version with polling every 15 minutes
> 
> I dont think the 15min version can even run 24h. The climate device alone does 16 requests per update and the water heater 3, so we have too many requests in the current version aswell ;)

With the fetchAndCacheFeatures() method it should run without any trouble

**Comment by crazyfx1** [comment]
@oischinger I've changed the API now to have the service cache data itself. So both water_heater and climate get to use the same cache.

Usage:
```Python
scan_interval = 60
t= HeatPump("xxx","xxx","token.save", 0, scan_interval)
print(t.getDomesticHotWaterConfiguredTemperature()) 
```

The only downside I see from this approach:
* It can occur that the cache is refreshed within one update-call in home-assistant. So you might see data which is not from the same api-result.

**Comment by adorobis** [comment]
> The adaptions are straight forward. Just call t.fetchAndCacheFeatures() as the first thing in the climate and water heater component.
> 
> I'm currently testing it with a 40 seconds update interval. Let's see if I get banned before 24h ;)

I've just implemented those changes on my HA but I've set it up with scan_interval 120. So far so good, let's see in 24 hours. Many thanks for quick solution!

**Comment by oischinger** [comment]
@somm15 What do you think of this implementation.
The last commit is imho a quite elegant solution. I would introduce a scan_interval parameter in the Home Assistant integration. Let's see if it survives 24hours with a scan_interval of 60 seconds, then we could set that as a default.

**Comment by somm15** [comment]
Hi Guys,

I'll have a look tomorrow. Lock down with 4 kids isn't easy, so I'm a little bit slow for the moment.

**Comment by somm15** [comment]
So after a short review, I will merge but I'll need to refactor later. 
The device ID is still hardcoded to 0 in the PyViCareSerice (and its new child). 
So far nobody never requested multi device support but the current design is not good.

I think we should have:
- Installation
  - Gateway(s)
    - Device(s)
Then I will probably move the GetFeature to the device object.

**Comment by oischinger** [comment]
Thanks @somm15 for the merge and pypi release. I'm also slowed down by the corona lockdown of my family but thanks to @crazyfx1 I think we already have a reliable solution now.

I'll update the vicare custom component today evening and I'll contribute an update to Home Assistant Core as soon as we have a good idea what is a good value for the update frequency.

**Pull request merged**
